### ISSUE TITLE
哪里可以下载PH2数据集呢

### ISSUE THREAD

**Issue by 2anchao** [FahdHabib/PH2-Dataset-Project#1]

**Comment by FahdHabib** [comment]
I converted your issue from Chinese to English and came to know you were looking for the link to download the dataset. Here it is:
https://www.fc.up.pt/addi/ph2%20database.html

**Comment by 2anchao** [comment]
> I converted your issue from Chinese to English and came to know you were looking for the link to download the dataset. Here it is:
> https://www.fc.up.pt/addi/ph2%20database.html

yes, thank you for your answer.
